version: "3.4"

services:
  dotnet-img-proxy:
    image: "mcr.microsoft.com/dotnet/sdk:5.0"
    command: tail -f /dev/null
    volumes:
      - ../../:/app:delegated
    working_dir: "/app/dotnet-img-proxy"

